# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(480, 532)
        self.centralwidget = QtWidgets.QWidget(ChatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.btn_connect.setObjectName("btn_connect")
        self.textEdit_chatBox = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_chatBox.setGeometry(QtCore.QRect(140, 70, 321, 351))
        self.textEdit_chatBox.setReadOnly(True)
        self.textEdit_chatBox.setObjectName("textEdit_chatBox")
        self.listWidget_clients = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_clients.setGeometry(QtCore.QRect(10, 70, 121, 351))
        self.listWidget_clients.setObjectName("listWidget_clients")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_text = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_text.setGeometry(QtCore.QRect(20, 440, 341, 31))
        self.lineEdit_text.setObjectName("lineEdit_text")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(370, 440, 81, 31))
        self.btn_send.setObjectName("btn_send")
        self.btn_joinRoom = QtWidgets.QPushButton(self.centralwidget)
        self.btn_joinRoom.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.btn_joinRoom.setObjectName("btn_joinRoom")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        ChatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        ChatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChatWindow)
        self.statusbar.setObjectName("statusbar")
        ChatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "MainWindow"))
        self.btn_connect.setText(_translate("ChatWindow", "Connect"))
        self.textEdit_chatBox.setDocumentTitle(_translate("ChatWindow", "chat box"))
        self.textEdit_chatBox.setHtml(_translate("ChatWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>chat box</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("ChatWindow", "clients"))
        self.label_2.setText(_translate("ChatWindow", "chat box"))
        self.btn_send.setText(_translate("ChatWindow", "send"))
        self.btn_joinRoom.setText(_translate("ChatWindow", "join room"))
        self.label_3.setText(_translate("ChatWindow", "TextLabel"))
