# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_clientWindow(object):
    def setupUi(self, clientWindow):
        clientWindow.setObjectName("clientWindow")
        clientWindow.resize(349, 406)
        self.centralwidget = QtWidgets.QWidget(clientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_client_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_client_connect.setGeometry(QtCore.QRect(180, 10, 75, 23))
        self.btn_client_connect.setObjectName("btn_client_connect")
        self.lineEdit_nickName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nickName.setGeometry(QtCore.QRect(60, 10, 113, 20))
        self.lineEdit_nickName.setObjectName("lineEdit_nickName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 321, 251))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 310, 241, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btn_client_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_client_send.setGeometry(QtCore.QRect(270, 310, 61, 31))
        self.btn_client_send.setObjectName("btn_client_send")
        self.btn_send_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send_img.setGeometry(QtCore.QRect(20, 340, 75, 31))
        self.btn_send_img.setObjectName("btn_send_img")
        clientWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(clientWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 21))
        self.menubar.setObjectName("menubar")
        clientWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(clientWindow)
        self.statusbar.setObjectName("statusbar")
        clientWindow.setStatusBar(self.statusbar)

        self.retranslateUi(clientWindow)
        QtCore.QMetaObject.connectSlotsByName(clientWindow)

    def retranslateUi(self, clientWindow):
        _translate = QtCore.QCoreApplication.translate
        clientWindow.setWindowTitle(_translate("clientWindow", "MainWindow"))
        self.btn_client_connect.setText(_translate("clientWindow", "connect"))
        self.label.setText(_translate("clientWindow", "Name"))
        self.btn_client_send.setText(_translate("clientWindow", "Send"))
        self.btn_client_send.setShortcut(_translate("clientWindow", "Return"))
        self.btn_send_img.setText(_translate("clientWindow", "Send image"))
